export const CategoryData = [
    { categoryName: "All ", link: "#" },
    { categoryName: "Music  ", link: "#" },
    { categoryName: "Lo-fi ", link: "#" },
    { categoryName: "Live ", link: "#" },
    { categoryName: "Free music ", link: "#" },
    { categoryName: "Playlists ", link: "#" },
    { categoryName: "Computer programming ", link: "#" },
    { categoryName: "Gaming ", link: "#" },
    { categoryName: "Deep House ", link: "#" },
    { categoryName: "Freestyle ", link: "#" },
    { categoryName: "Rap ", link: "#" },
    { categoryName: "Rhythm & Blues ", link: "#" },
    { categoryName: "Game shows ", link: "#" },
    { categoryName: "Piano ", link: "#" },
    { categoryName: "News ", link: "#" },
    { categoryName: "Indie Music ", link: "#" },
    { categoryName: "League of Legends ", link: "#" },
    { categoryName: "Rapping ", link: "#" },
    { categoryName: "Anime ", link: "#" },
    { categoryName: "Comedy ", link: "#" },
    { categoryName: "Recently uploaded ", link: "#" },
    { categoryName: "Watched", link: "#" },
];
