export const CardData = [
    {
        userName: "Nam Dev",
        id: 1,
        title: "accusamus beatae ad facilis cum similique qui suntaaaaaaaaa",
        coverImage: "https://via.placeholder.com/600/92c952",
        avtImage: "https://via.placeholder.com/150/92c952",
    },
    {
        userName: "Nam Dev",
        id: 2,
        title: "reprehenderit est deserunt velit ipsam",
        coverImage: "https://via.placeholder.com/600/771796",
        avtImage: "https://via.placeholder.com/150/771796",
    },
    {
        userName: "Nam Dev",
        id: 3,
        title: "officia porro iure quia iusto qui ipsa ut modi",
        coverImage: "https://via.placeholder.com/600/24f355",
        avtImage: "https://via.placeholder.com/150/24f355",
    },
    {
        userName: "Nam Dev",
        id: 4,
        title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
        coverImage: "https://via.placeholder.com/600/d32776",
        avtImage: "https://via.placeholder.com/150/d32776",
    },
    {
        userName: "Nam Dev",
        id: 5,
        title: "natus nisi omnis corporis facere molestiae rerum in",
        coverImage: "https://via.placeholder.com/600/f66b97",
        avtImage: "https://via.placeholder.com/150/f66b97",
    },
    {
        userName: "Nam Dev",
        id: 6,
        title: "accusamus ea aliquid et amet sequi nemo",
        coverImage: "https://via.placeholder.com/600/56a8c2",
        avtImage: "https://via.placeholder.com/150/56a8c2",
    },
    {
        userName: "Nam Dev",
        id: 7,
        title: "officia delectus consequatur vero aut veniam explicabo molestias",
        coverImage: "https://via.placeholder.com/600/b0f7cc",
        avtImage: "https://via.placeholder.com/150/b0f7cc",
    },
    {
        userName: "Nam Dev",
        id: 8,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        coverImage: "https://via.placeholder.com/600/54176f",
        avtImage: "https://via.placeholder.com/150/54176f",
    },
    {
        userName: "Nam Dev",
        id: 9,
        title: "qui eius qui autem sed",
        coverImage: "https://via.placeholder.com/600/51aa97",
        avtImage: "https://via.placeholder.com/150/51aa97",
    },
    {
        userName: "Nam Dev",
        id: 10,
        title: "beatae et provident et ut vel",
        coverImage: "https://via.placeholder.com/600/810b14",
        avtImage: "https://via.placeholder.com/150/810b14",
    },
    {
        userName: "Nam Dev",
        id: 11,
        title: "nihil at amet non hic quia qui",
        coverImage: "https://via.placeholder.com/600/1ee8a4",
        avtImage: "https://via.placeholder.com/150/1ee8a4",
    },
    {
        userName: "Nam Dev",
        id: 12,
        title: "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
        coverImage: "https://via.placeholder.com/600/66b7d2",
        avtImage: "https://via.placeholder.com/150/66b7d2",
    },
    {
        userName: "Nam Dev",
        id: 13,
        title: "repudiandae iusto deleniti rerum",
        coverImage: "https://via.placeholder.com/600/197d29",
        avtImage: "https://via.placeholder.com/150/197d29",
    },
    {
        userName: "Nam Dev",
        id: 14,
        title: "est necessitatibus architecto ut laborum",
        coverImage: "https://via.placeholder.com/600/61a65",
        avtImage: "https://via.placeholder.com/150/61a65",
    },
    {
        userName: "Nam Dev",
        id: 15,
        title: "harum dicta similique quis dolore earum ex qui",
        coverImage: "https://via.placeholder.com/600/f9cee5",
        avtImage: "https://via.placeholder.com/150/f9cee5",
    },
    {
        userName: "Nam Dev",
        id: 16,
        title: "iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt",
        coverImage: "https://via.placeholder.com/600/fdf73e",
        avtImage: "https://via.placeholder.com/150/fdf73e",
    },
    {
        userName: "Nam Dev",
        id: 17,
        title: "natus doloribus necessitatibus ipsa",
        coverImage: "https://via.placeholder.com/600/9c184f",
        avtImage: "https://via.placeholder.com/150/9c184f",
    },
    {
        userName: "Nam Dev",
        id: 18,
        title: "laboriosam odit nam necessitatibus et illum dolores reiciendis",
        coverImage: "https://via.placeholder.com/600/1fe46f",
        avtImage: "https://via.placeholder.com/150/1fe46f",
    },
    {
        userName: "Nam Dev",
        id: 19,
        title: "perferendis nesciunt eveniet et optio a",
        coverImage: "https://via.placeholder.com/600/56acb2",
        avtImage: "https://via.placeholder.com/150/56acb2",
    },
    {
        userName: "Nam Dev",
        id: 20,
        title: "assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error",
        coverImage: "https://via.placeholder.com/600/8985dc",
        avtImage: "https://via.placeholder.com/150/8985dc",
    },
    {
        userName: "Nam Dev",
        id: 21,
        title: "ad et natus qui",
        coverImage: "https://via.placeholder.com/600/5e12c6",
        avtImage: "https://via.placeholder.com/150/5e12c6",
    },
    {
        userName: "Nam Dev",
        id: 22,
        title: "et ea illo et sit voluptas animi blanditiis porro",
        coverImage: "https://via.placeholder.com/600/45601a",
        avtImage: "https://via.placeholder.com/150/45601a",
    },
    {
        userName: "Nam Dev",
        id: 23,
        title: "harum velit vero totam",
        coverImage: "https://via.placeholder.com/600/e924e6",
        avtImage: "https://via.placeholder.com/150/e924e6",
    },
    {
        userName: "Nam Dev",
        id: 24,
        title: "beatae officiis ut aut",
        coverImage: "https://via.placeholder.com/600/8f209a",
        avtImage: "https://via.placeholder.com/150/8f209a",
    },
    {
        userName: "Nam Dev",
        id: 25,
        title: "facere non quis fuga fugit vitae",
        coverImage: "https://via.placeholder.com/600/5e3a73",
        avtImage: "https://via.placeholder.com/150/5e3a73",
    },
    {
        userName: "Nam Dev",
        id: 26,
        title: "asperiores nobis voluptate qui",
        coverImage: "https://via.placeholder.com/600/474645",
        avtImage: "https://via.placeholder.com/150/474645",
    },
    {
        userName: "Nam Dev",
        id: 27,
        title: "sit asperiores est quos quis nisi veniam error",
        coverImage: "https://via.placeholder.com/600/c984bf",
        avtImage: "https://via.placeholder.com/150/c984bf",
    },
    {
        userName: "Nam Dev",
        id: 28,
        title: "non neque eligendi molestiae repudiandae illum voluptatem qui aut",
        coverImage: "https://via.placeholder.com/600/392537",
        avtImage: "https://via.placeholder.com/150/392537",
    },
    {
        userName: "Nam Dev",
        id: 29,
        title: "aut ipsam quos ab placeat omnis",
        coverImage: "https://via.placeholder.com/600/602b9e",
        avtImage: "https://via.placeholder.com/150/602b9e",
    },
    {
        userName: "Nam Dev",
        id: 30,
        title: "odio enim voluptatem quidem aut nihil illum",
        coverImage: "https://via.placeholder.com/600/372c93",
        avtImage: "https://via.placeholder.com/150/372c93",
    },
    {
        userName: "Nam Dev",
        id: 31,
        title: "voluptate voluptates sequi",
        coverImage: "https://via.placeholder.com/600/a7c272",
        avtImage: "https://via.placeholder.com/150/a7c272",
    },
    {
        userName: "Nam Dev",
        id: 32,
        title: "ad enim dignissimos voluptatem similique",
        coverImage: "https://via.placeholder.com/600/c70a4d",
        avtImage: "https://via.placeholder.com/150/c70a4d",
    },
    {
        userName: "Nam Dev",
        id: 33,
        title: "culpa ipsam nobis qui fuga magni et mollitia",
        coverImage: "https://via.placeholder.com/600/501fe1",
        avtImage: "https://via.placeholder.com/150/501fe1",
    },
    {
        userName: "Nam Dev",
        id: 34,
        title: "vitae est facere quia itaque adipisci perferendis id maiores",
        coverImage: "https://via.placeholder.com/600/35185e",
        avtImage: "https://via.placeholder.com/150/35185e",
    },
    {
        userName: "Nam Dev",
        id: 35,
        title: "tenetur minus voluptatum et",
        coverImage: "https://via.placeholder.com/600/c96cad",
        avtImage: "https://via.placeholder.com/150/c96cad",
    },
    {
        userName: "Nam Dev",
        id: 36,
        title: "expedita rerum eaque",
        coverImage: "https://via.placeholder.com/600/4d564d",
        avtImage: "https://via.placeholder.com/150/4d564d",
    },
    {
        userName: "Nam Dev",
        id: 37,
        title: "totam voluptas iusto deserunt dolores",
        coverImage: "https://via.placeholder.com/600/ea51da",
        avtImage: "https://via.placeholder.com/150/ea51da",
    },
    {
        userName: "Nam Dev",
        id: 38,
        title: "natus magnam iure rerum pariatur molestias dolore nisi",
        coverImage: "https://via.placeholder.com/600/4f5b8d",
        avtImage: "https://via.placeholder.com/150/4f5b8d",
    },
    {
        userName: "Nam Dev",
        id: 39,
        title: "molestiae nam ullam et rerum doloribus",
        coverImage: "https://via.placeholder.com/600/1e71a2",
        avtImage: "https://via.placeholder.com/150/1e71a2",
    },
    {
        userName: "Nam Dev",
        id: 40,
        title: "est quas voluptates dignissimos sint praesentium nisi recusandae",
        coverImage: "https://via.placeholder.com/600/3a0b95",
        avtImage: "https://via.placeholder.com/150/3a0b95",
    },
    {
        userName: "Nam Dev",
        id: 41,
        title: "in voluptatem doloremque cum atque architecto deleniti",
        coverImage: "https://via.placeholder.com/600/659403",
        avtImage: "https://via.placeholder.com/150/659403",
    },
    {
        userName: "Nam Dev",
        id: 42,
        title: "voluptatibus a autem molestias voluptas architecto culpa",
        coverImage: "https://via.placeholder.com/600/ca50ac",
        avtImage: "https://via.placeholder.com/150/ca50ac",
    },
    {
        userName: "Nam Dev",
        id: 43,
        title: "eius hic autem ad beatae voluptas",
        coverImage: "https://via.placeholder.com/600/6ad437",
        avtImage: "https://via.placeholder.com/150/6ad437",
    },
    {
        userName: "Nam Dev",
        id: 44,
        title: "neque eum provident et inventore sed ipsam dignissimos quo",
        coverImage: "https://via.placeholder.com/600/29fe9f",
        avtImage: "https://via.placeholder.com/150/29fe9f",
    },
    {
        userName: "Nam Dev",
        id: 45,
        title: "praesentium fugit quis aut voluptatum commodi dolore corrupti",
        coverImage: "https://via.placeholder.com/600/c4084a",
        avtImage: "https://via.placeholder.com/150/c4084a",
    },
    {
        userName: "Nam Dev",
        id: 46,
        title: "quidem maiores in quia fugit dolore explicabo occaecati",
        coverImage: "https://via.placeholder.com/600/e9b68",
        avtImage: "https://via.placeholder.com/150/e9b68",
    },
    {
        userName: "Nam Dev",
        id: 47,
        title: "et soluta est",
        coverImage: "https://via.placeholder.com/600/b4412f",
        avtImage: "https://via.placeholder.com/150/b4412f",
    },
    {
        userName: "Nam Dev",
        id: 48,
        title: "ut esse id",
        coverImage: "https://via.placeholder.com/600/68e0a8",
        avtImage: "https://via.placeholder.com/150/68e0a8",
    },
    {
        userName: "Nam Dev",
        id: 49,
        title: "quasi quae est modi quis quam in impedit",
        coverImage: "https://via.placeholder.com/600/2cd88b",
        avtImage: "https://via.placeholder.com/150/2cd88b",
    },
    {
        userName: "Nam Dev",
        id: 50,
        title: "et inventore quae ut tempore eius voluptatum",
        coverImage: "https://via.placeholder.com/600/9e59da",
        avtImage: "https://via.placeholder.com/150/9e59da",
    },
    {
        userName: "Nam Dev",
        id: 51,
        title: "non sunt voluptatem placeat consequuntur rem incidunt",
        coverImage: "https://via.placeholder.com/600/8e973b",
        avtImage: "https://via.placeholder.com/150/8e973b",
    },
    {
        userName: "Nam Dev",
        id: 52,
        title: "eveniet pariatur quia nobis reiciendis laboriosam ea",
        coverImage: "https://via.placeholder.com/600/121fa4",
        avtImage: "https://via.placeholder.com/150/121fa4",
    },
    {
        userName: "Nam Dev",
        id: 53,
        title: "soluta et harum aliquid officiis ab omnis consequatur",
        coverImage: "https://via.placeholder.com/600/6efc5f",
        avtImage: "https://via.placeholder.com/150/6efc5f",
    },
    {
        userName: "Nam Dev",
        id: 54,
        title: "ut ex quibusdam dolore mollitia",
        coverImage: "https://via.placeholder.com/600/aa8f2e",
        avtImage: "https://via.placeholder.com/150/aa8f2e",
    },
    {
        userName: "Nam Dev",
        id: 55,
        title: "voluptatem consequatur totam qui aut iure est vel",
        coverImage: "https://via.placeholder.com/600/5e04a4",
        avtImage: "https://via.placeholder.com/150/5e04a4",
    },
    {
        userName: "Nam Dev",
        id: 56,
        title: "vel voluptatem esse consequuntur est officia quo aut quisquam",
        coverImage: "https://via.placeholder.com/600/f9f067",
        avtImage: "https://via.placeholder.com/150/f9f067",
    },
    {
        userName: "Nam Dev",
        id: 57,
        title: "vero est optio expedita quis ut molestiae",
        coverImage: "https://via.placeholder.com/600/95acce",
        avtImage: "https://via.placeholder.com/150/95acce",
    },
    {
        userName: "Nam Dev",
        id: 58,
        title: "rem pariatur facere eaque",
        coverImage: "https://via.placeholder.com/600/cde4c1",
        avtImage: "https://via.placeholder.com/150/cde4c1",
    },
    {
        userName: "Nam Dev",
        id: 59,
        title: "modi totam dolor eaque et ipsum est cupiditate",
        coverImage: "https://via.placeholder.com/600/a46a91",
        avtImage: "https://via.placeholder.com/150/a46a91",
    },
    {
        userName: "Nam Dev",
        id: 60,
        title: "ea enim temporibus asperiores placeat consectetur commodi ullam",
        coverImage: "https://via.placeholder.com/600/323599",
        avtImage: "https://via.placeholder.com/150/323599",
    },
    {
        userName: "Nam Dev",
        id: 61,
        title: "quia minus sed eveniet accusantium incidunt beatae odio",
        coverImage: "https://via.placeholder.com/600/e403d1",
        avtImage: "https://via.placeholder.com/150/e403d1",
    },
    {
        userName: "Nam Dev",
        id: 62,
        title: "dolorem cumque quo nihil inventore enim",
        coverImage: "https://via.placeholder.com/600/65ad4f",
        avtImage: "https://via.placeholder.com/150/65ad4f",
    },
    {
        userName: "Nam Dev",
        id: 63,
        title: "facere animi autem quod dolor",
        coverImage: "https://via.placeholder.com/600/4e557c",
        avtImage: "https://via.placeholder.com/150/4e557c",
    },
    {
        userName: "Nam Dev",
        id: 64,
        title: "doloremque culpa quia",
        coverImage: "https://via.placeholder.com/600/cd5a92",
        avtImage: "https://via.placeholder.com/150/cd5a92",
    },
    {
        userName: "Nam Dev",
        id: 65,
        title: "sed voluptatum enim eaque cumque qui sunt",
        coverImage: "https://via.placeholder.com/600/149540",
        avtImage: "https://via.placeholder.com/150/149540",
    },
    {
        userName: "Nam Dev",
        id: 66,
        title: "provident rerum voluptatem illo asperiores qui maiores",
        coverImage: "https://via.placeholder.com/600/ee0a7e",
        avtImage: "https://via.placeholder.com/150/ee0a7e",
    },
    {
        userName: "Nam Dev",
        id: 67,
        title: "veritatis labore ipsum unde aut quam dolores",
        coverImage: "https://via.placeholder.com/600/1279e9",
        avtImage: "https://via.placeholder.com/150/1279e9",
    },
    {
        userName: "Nam Dev",
        id: 68,
        title: "architecto aut quod qui ullam vitae expedita delectus",
        coverImage: "https://via.placeholder.com/600/e9603b",
        avtImage: "https://via.placeholder.com/150/e9603b",
    },
    {
        userName: "Nam Dev",
        id: 69,
        title: "et autem dolores aut porro est qui",
        coverImage: "https://via.placeholder.com/600/46e3b1",
        avtImage: "https://via.placeholder.com/150/46e3b1",
    },
    {
        userName: "Nam Dev",
        id: 70,
        title: "quam quos dolor eum ea in",
        coverImage: "https://via.placeholder.com/600/7375af",
        avtImage: "https://via.placeholder.com/150/7375af",
    },
    {
        userName: "Nam Dev",
        id: 71,
        title: "illo qui vel laboriosam vel fugit deserunt",
        coverImage: "https://via.placeholder.com/600/363789",
        avtImage: "https://via.placeholder.com/150/363789",
    },
    {
        userName: "Nam Dev",
        id: 72,
        title: "iusto sint enim nesciunt facilis exercitationem",
        coverImage: "https://via.placeholder.com/600/45935c",
        avtImage: "https://via.placeholder.com/150/45935c",
    },
    {
        userName: "Nam Dev",
        id: 73,
        title: "rerum exercitationem libero dolor",
        coverImage: "https://via.placeholder.com/600/1224bd",
        avtImage: "https://via.placeholder.com/150/1224bd",
    },
    {
        userName: "Nam Dev",
        id: 74,
        title: "eligendi quas consequatur aut consequuntur",
        coverImage: "https://via.placeholder.com/600/65ac19",
        avtImage: "https://via.placeholder.com/150/65ac19",
    },
    {
        userName: "Nam Dev",
        id: 75,
        title: "aut magni quibusdam cupiditate ea",
        coverImage: "https://via.placeholder.com/600/a9ef52",
        avtImage: "https://via.placeholder.com/150/a9ef52",
    },
    {
        userName: "Nam Dev",
        id: 76,
        title: "magni nulla et dolores",
        coverImage: "https://via.placeholder.com/600/7644fe",
        avtImage: "https://via.placeholder.com/150/7644fe",
    },
    {
        userName: "Nam Dev",
        id: 77,
        title: "ipsum consequatur vel omnis mollitia repellat dolores quasi",
        coverImage: "https://via.placeholder.com/600/36d137",
        avtImage: "https://via.placeholder.com/150/36d137",
    },
    {
        userName: "Nam Dev",
        id: 78,
        title: "aperiam aut est amet tenetur et dolorem",
        coverImage: "https://via.placeholder.com/600/637984",
        avtImage: "https://via.placeholder.com/150/637984",
    },
    {
        userName: "Nam Dev",
        id: 79,
        title: "est vel et laboriosam quo aspernatur distinctio molestiae",
        coverImage: "https://via.placeholder.com/600/c611a9",
        avtImage: "https://via.placeholder.com/150/c611a9",
    },
    {
        userName: "Nam Dev",
        id: 80,
        title: "et corrupti nihil cumque",
        coverImage: "https://via.placeholder.com/600/a0c998",
        avtImage: "https://via.placeholder.com/150/a0c998",
    },
    {
        userName: "Nam Dev",
        id: 81,
        title: "error magni fugiat dolorem impedit molestiae illo ullam debitis",
        coverImage: "https://via.placeholder.com/600/31a74c",
        avtImage: "https://via.placeholder.com/150/31a74c",
    },
    {
        userName: "Nam Dev",
        id: 82,
        title: "voluptate voluptas molestias vitae illo iusto",
        coverImage: "https://via.placeholder.com/600/88b703",
        avtImage: "https://via.placeholder.com/150/88b703",
    },
    {
        userName: "Nam Dev",
        id: 83,
        title: "quia quasi enim voluptatem repellat sit sint",
        coverImage: "https://via.placeholder.com/600/a19891",
        avtImage: "https://via.placeholder.com/150/a19891",
    },
    {
        userName: "Nam Dev",
        id: 84,
        title: "aliquam dolorem ut modi ratione et assumenda impedit",
        coverImage: "https://via.placeholder.com/600/b5205d",
        avtImage: "https://via.placeholder.com/150/b5205d",
    },
    {
        userName: "Nam Dev",
        id: 85,
        title: "ullam delectus architecto sint error",
        coverImage: "https://via.placeholder.com/600/eb7e7f",
        avtImage: "https://via.placeholder.com/150/eb7e7f",
    },
    {
        userName: "Nam Dev",
        id: 86,
        title: "qui vel ut odio consequuntur",
        coverImage: "https://via.placeholder.com/600/fd5751",
        avtImage: "https://via.placeholder.com/150/fd5751",
    },
    {
        userName: "Nam Dev",
        id: 87,
        title: "eos nihil sunt accusantium omnis",
        coverImage: "https://via.placeholder.com/600/224566",
        avtImage: "https://via.placeholder.com/150/224566",
    },
    {
        userName: "Nam Dev",
        id: 88,
        title: "inventore veritatis magnam enim quasi",
        coverImage: "https://via.placeholder.com/600/75334a",
        avtImage: "https://via.placeholder.com/150/75334a",
    },
    {
        userName: "Nam Dev",
        id: 89,
        title: "id at cum incidunt nulla dolor vero tenetur",
        coverImage: "https://via.placeholder.com/600/21d35",
        avtImage: "https://via.placeholder.com/150/21d35",
    },
    {
        userName: "Nam Dev",
        id: 90,
        title: "et quae eligendi vitae maxime in",
        coverImage: "https://via.placeholder.com/600/bfe0dc",
        avtImage: "https://via.placeholder.com/150/bfe0dc",
    },
    {
        userName: "Nam Dev",
        id: 91,
        title: "sunt quo laborum commodi porro consequatur nam delectus et",
        coverImage: "https://via.placeholder.com/600/40591",
        avtImage: "https://via.placeholder.com/150/40591",
    },
    {
        userName: "Nam Dev",
        id: 92,
        title: "quod non quae",
        coverImage: "https://via.placeholder.com/600/de79c7",
        avtImage: "https://via.placeholder.com/150/de79c7",
    },
    {
        userName: "Nam Dev",
        id: 93,
        title: "molestias et aliquam natus repellendus accusamus dolore",
        coverImage: "https://via.placeholder.com/600/2edde0",
        avtImage: "https://via.placeholder.com/150/2edde0",
    },
    {
        userName: "Nam Dev",
        id: 94,
        title: "et quisquam aspernatur",
        coverImage: "https://via.placeholder.com/600/cc12f5",
        avtImage: "https://via.placeholder.com/150/cc12f5",
    },
    {
        userName: "Nam Dev",
        id: 95,
        title: "magni odio non",
        coverImage: "https://via.placeholder.com/600/9cda61",
        avtImage: "https://via.placeholder.com/150/9cda61",
    },
    {
        userName: "Nam Dev",
        id: 96,
        title: "dolore esse a in eos sed",
        coverImage: "https://via.placeholder.com/600/1fb08b",
        avtImage: "https://via.placeholder.com/150/1fb08b",
    },
    {
        userName: "Nam Dev",
        id: 97,
        title: "labore magnam officiis nemo et",
        coverImage: "https://via.placeholder.com/600/e2223e",
        avtImage: "https://via.placeholder.com/150/e2223e",
    },
    {
        userName: "Nam Dev",
        id: 98,
        title: "sed commodi libero id nesciunt modi vitae",
        coverImage: "https://via.placeholder.com/600/a77d08",
        avtImage: "https://via.placeholder.com/150/a77d08",
    },
    {
        userName: "Nam Dev",
        id: 99,
        title: "magnam dolor sed enim vel optio consequuntur",
        coverImage: "https://via.placeholder.com/600/b04f2e",
        avtImage: "https://via.placeholder.com/150/b04f2e",
    },
];
