export const shortsData = [
    {
        userName: "Nam Dev",
        id: 1,
        title: "accusamus beatae ad facilis cum similique qui sunt",
        coverImage: "https://via.placeholder.com/600/92c952",
        avtImage: "https://via.placeholder.com/150/92c952",
    },
    {
        userName: "Nam Dev",
        id: 2,
        title: "reprehenderit est deserunt velit ipsam",
        coverImage: "https://via.placeholder.com/600/771796",
        avtImage: "https://via.placeholder.com/150/771796",
    },
    {
        userName: "Nam Dev",
        id: 3,
        title: "officia porro iure quia iusto qui ipsa ut modi",
        coverImage: "https://via.placeholder.com/600/24f355",
        avtImage: "https://via.placeholder.com/150/24f355",
    },
    {
        userName: "Nam Dev",
        id: 4,
        title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
        coverImage: "https://via.placeholder.com/600/d32776",
        avtImage: "https://via.placeholder.com/150/d32776",
    },
    {
        userName: "Nam Dev",
        id: 5,
        title: "natus nisi omnis corporis facere molestiae rerum in",
        coverImage: "https://via.placeholder.com/600/f66b97",
        avtImage: "https://via.placeholder.com/150/f66b97",
    },
    {
        userName: "Nam Dev",
        id: 6,
        title: "accusamus ea aliquid et amet sequi nemo",
        coverImage: "https://via.placeholder.com/600/56a8c2",
        avtImage: "https://via.placeholder.com/150/56a8c2",
    },
    {
        userName: "Nam Dev",
        id: 7,
        title: "officia delectus consequatur vero aut veniam explicabo molestias",
        coverImage: "https://via.placeholder.com/600/b0f7cc",
        avtImage: "https://via.placeholder.com/150/b0f7cc",
    },
    {
        userName: "Nam Dev",
        id: 8,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        coverImage: "https://via.placeholder.com/600/54176f",
        avtImage: "https://via.placeholder.com/150/54176f",
    },
    {
        userName: "Nam Dev",
        id: 9,
        title: "qui eius qui autem sed",
        coverImage: "https://via.placeholder.com/600/51aa97",
        avtImage: "https://via.placeholder.com/150/51aa97",
    },
    {
        userName: "Nam Dev",
        id: 10,
        title: "beatae et provident et ut vel",
        coverImage: "https://via.placeholder.com/600/810b14",
        avtImage: "https://via.placeholder.com/150/810b14",
    },
    {
        userName: "Nam Dev",
        id: 11,
        title: "nihil at amet non hic quia qui",
        coverImage: "https://via.placeholder.com/600/1ee8a4",
        avtImage: "https://via.placeholder.com/150/1ee8a4",
    },
    {
        userName: "Nam Dev",
        id: 12,
        title: "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
        coverImage: "https://via.placeholder.com/600/66b7d2",
        avtImage: "https://via.placeholder.com/150/66b7d2",
    },
];
